require("config.lazy")
require("config.undotree")
require("config.lsp_zero")
require("config.lua_snip")
require("config.vim_fugitive")
require("config")
require("config.harpoon")
vim.cmd(':colorscheme everforest')
require("config.colors")
